# Generated by Django 2.2.2 on 2020-04-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_place_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photo/%Y/%m', verbose_name='IMAGE'),
        ),
    ]
